//! Dialogue index: every voice recording in the game with the line it belongs
//! to (speaker, topic, quest, subtitle text) and its wem id.
//!
//! `assets/voice_index.bin` is generated by `tools/sfxindex` from the Wwise
//! voice events and the plugins' dialogue records, stored deflated and
//! inflated once on first use (~30 ms).

#[allow(dead_code)]
pub mod format;

use format::{RawVoiceIndex, LINE_NAMED_SPEAKER, NONE, VOICE_ALT};
use std::collections::HashMap;
use std::io::Read;
use std::sync::OnceLock;

static VOICE_BLOB: &[u8] = include_bytes!("../../assets/voice_index.bin");
static INDEX: OnceLock<VoiceIndex> = OnceLock::new();

#[derive(Clone, Debug)]
pub struct Line {
    pub formid: u32,
    pub plugin: &'static str,
    pub response: u8,
    /// The line is conditioned on specific NPCs (`speaker` names them).
    pub named_speaker: bool,
    pub quest: &'static str,
    pub topic: &'static str,
    pub text: &'static str,
    /// NPC names, a faction/class hint, or empty for "anyone of that race and sex".
    pub speaker: &'static str,
}

#[derive(Clone, Debug)]
pub struct Voice {
    pub wem_id: u32,
    pub line: u32,
    /// Race folder the event lives in.
    pub race: &'static str,
    pub female: bool,
    /// Race of the actor who recorded the file (can differ from `race`).
    pub voice_race: &'static str,
    /// Indices into the index's race table (lower-case copies for search).
    race_id: u8,
    voice_race_id: u8,
    pub alt: bool,
    pub duration_ms: u32,
}

impl Voice {
    /// `Imperial male`, `Dark Elf female (alt voice)`.
    pub fn voice_type(&self) -> String {
        let mut s = format!("{} {}", self.voice_race, if self.female { "female" } else { "male" });
        if self.alt {
            s.push_str(" (alt voice)");
        }
        s
    }
}

/// How a speaker group was derived.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SpeakerKind {
    /// A named NPC from the line's conditions.
    Npc,
    /// Lines for members of a faction.
    Faction,
    /// Lines for NPCs of a class.
    Class,
    /// Lines any NPC of a race and sex can say.
    Race,
}

impl SpeakerKind {
    pub fn label(self) -> &'static str {
        match self {
            SpeakerKind::Npc => "NPC",
            SpeakerKind::Faction => "Faction",
            SpeakerKind::Class => "Class",
            SpeakerKind::Race => "Race",
        }
    }
}

/// A speaker group of the Dialogue tab: every voice line said by one NPC
/// (or by a faction, class, or race+sex), in display order.
pub struct Speaker {
    pub label: &'static str,
    pub kind: SpeakerKind,
    pub voices: Vec<u32>,
}

pub struct VoiceIndex {
    lines: Vec<Line>,
    voices: Vec<Voice>,
    /// Voice indices sorted by wem id (a shared recording appears once per voice).
    by_wem: Vec<u32>,
    /// Lower-case searchable text per line: speaker, topic, quest, text, plugin.
    haystack: Vec<String>,
    /// Lower-case race labels, indexed like the race table.
    races_lc: Vec<String>,
    /// NPCs first (alphabetical), then factions, classes and race groups.
    speakers: Vec<Speaker>,
    /// Speaker ids of voice `i` are `voice_speaker_ids[offsets[i]..offsets[i + 1]]`.
    voice_speaker_offsets: Vec<u32>,
    voice_speaker_ids: Vec<u32>,
}

impl VoiceIndex {
    pub fn get() -> &'static VoiceIndex {
        INDEX.get_or_init(|| VoiceIndex::load(VOICE_BLOB).expect("embedded voice_index.bin is corrupt; rebuild it with tools/sfxindex"))
    }

    fn load(deflated: &'static [u8]) -> Result<VoiceIndex, format::FormatError> {
        let mut raw_bytes = Vec::with_capacity(deflated.len() * 4);
        flate2::read::DeflateDecoder::new(deflated)
            .read_to_end(&mut raw_bytes)
            .map_err(|e| format::FormatError(format!("inflate: {e}")))?;
        let blob: &'static [u8] = Box::leak(raw_bytes.into_boxed_slice());
        let raw = RawVoiceIndex::parse(blob)?;
        let h = raw.header;
        let str_or_empty = |id: u32| if id == NONE { "" } else { raw.string(id) };
        let races: Vec<&'static str> = (0..h.race_count as usize).map(|i| raw.string(raw.race(i))).collect();
        let plugins: Vec<&'static str> = (0..h.plugin_count as usize).map(|i| raw.string(raw.plugin(i))).collect();
        let lines: Vec<Line> = (0..h.line_count as usize)
            .map(|i| {
                let l = raw.line(i);
                Line {
                    formid: l.formid,
                    plugin: plugins.get(l.plugin as usize).copied().unwrap_or(""),
                    response: l.response,
                    named_speaker: l.flags & LINE_NAMED_SPEAKER != 0,
                    quest: str_or_empty(l.quest),
                    topic: str_or_empty(l.topic),
                    text: str_or_empty(l.text),
                    speaker: str_or_empty(l.speaker),
                }
            })
            .collect();
        let voices: Vec<Voice> = (0..h.voice_count as usize)
            .map(|i| {
                let v = raw.voice(i);
                Voice {
                    wem_id: v.wem_id,
                    line: v.line,
                    race: races[v.race as usize],
                    female: v.sex == 1,
                    voice_race: races[v.voice_race as usize],
                    race_id: v.race,
                    voice_race_id: v.voice_race,
                    alt: v.flags & VOICE_ALT != 0,
                    duration_ms: v.duration_ms,
                }
            })
            .collect();
        let by_wem = (0..h.voice_count as usize).map(|i| raw.by_wem(i)).collect();
        let haystack = lines
            .iter()
            .map(|l| format!("{}|{}|{}|{}|{}", l.speaker, l.topic, l.quest, l.text, l.plugin).to_lowercase())
            .collect();
        let races_lc: Vec<String> = races.iter().map(|r| r.to_lowercase()).collect();

        // Speaker groups: one per NPC named in the line's conditions, else the
        // faction/class hint, else "Any <race> <sex>".
        let mut race_labels: HashMap<(&'static str, bool), &'static str> = HashMap::new();
        let mut groups: HashMap<(SpeakerKind, &'static str), Vec<u32>> = HashMap::new();
        let mut per_voice: Vec<Vec<(SpeakerKind, &'static str)>> = Vec::with_capacity(voices.len());
        for (i, v) in voices.iter().enumerate() {
            let l = &lines[v.line as usize];
            let mut labels: Vec<(SpeakerKind, &'static str)> = Vec::with_capacity(1);
            if l.named_speaker && !l.speaker.is_empty() {
                labels.extend(l.speaker.split(", ").filter(|n| !n.is_empty()).map(|n| (SpeakerKind::Npc, n)));
            } else if let Some(f) = l.speaker.strip_suffix(" members") {
                labels.push((SpeakerKind::Faction, f));
            } else if !l.speaker.is_empty() {
                labels.push((SpeakerKind::Class, l.speaker));
            } else {
                let label = *race_labels
                    .entry((v.race, v.female))
                    .or_insert_with(|| Box::leak(format!("Any {} {}", v.race, if v.female { "female" } else { "male" }).into_boxed_str()));
                labels.push((SpeakerKind::Race, label));
            }
            for lab in &labels {
                groups.entry(*lab).or_default().push(i as u32);
            }
            per_voice.push(labels);
        }
        let mut speakers: Vec<Speaker> = groups.into_iter().map(|((kind, label), voices)| Speaker { label, kind, voices }).collect();
        speakers.sort_by(|a, b| a.kind.cmp(&b.kind).then_with(|| a.label.to_lowercase().cmp(&b.label.to_lowercase())).then_with(|| a.label.cmp(b.label)));
        let speaker_ids: HashMap<(SpeakerKind, &'static str), u32> = speakers.iter().enumerate().map(|(i, sp)| ((sp.kind, sp.label), i as u32)).collect();
        let mut voice_speaker_offsets = Vec::with_capacity(voices.len() + 1);
        let mut voice_speaker_ids = Vec::with_capacity(voices.len());
        for labels in &per_voice {
            voice_speaker_offsets.push(voice_speaker_ids.len() as u32);
            voice_speaker_ids.extend(labels.iter().map(|lab| speaker_ids[lab]));
        }
        voice_speaker_offsets.push(voice_speaker_ids.len() as u32);
        Ok(VoiceIndex { lines, voices, by_wem, haystack, races_lc, speakers, voice_speaker_offsets, voice_speaker_ids })
    }

    pub fn len(&self) -> usize {
        self.voices.len()
    }

    pub fn is_empty(&self) -> bool {
        self.voices.is_empty()
    }

    pub fn voice(&self, idx: u32) -> &Voice {
        &self.voices[idx as usize]
    }

    pub fn line_of(&self, voice: &Voice) -> &Line {
        &self.lines[voice.line as usize]
    }

    pub fn lines(&self) -> &[Line] {
        &self.lines
    }

    /// Every voice that plays this recording (the same wem serves several race
    /// folders), in display order.
    pub fn voices_of_wem(&self, wem_id: u32) -> &[u32] {
        let lo = self.by_wem.partition_point(|&i| self.voices[i as usize].wem_id < wem_id);
        let hi = self.by_wem.partition_point(|&i| self.voices[i as usize].wem_id <= wem_id);
        &self.by_wem[lo..hi]
    }

    /// First voice for a wem id.
    pub fn by_wem(&self, wem_id: u32) -> Option<u32> {
        self.voices_of_wem(wem_id).first().copied()
    }

    pub fn speakers(&self) -> &[Speaker] {
        &self.speakers
    }

    pub fn speaker(&self, idx: u32) -> &Speaker {
        &self.speakers[idx as usize]
    }

    /// Speaker groups a voice belongs to (a line conditioned on several NPCs is under each).
    pub fn speakers_of_voice(&self, voice: u32) -> &[u32] {
        let i = voice as usize;
        &self.voice_speaker_ids[self.voice_speaker_offsets[i] as usize..self.voice_speaker_offsets[i + 1] as usize]
    }

    /// The voices matching `query` grouped by speaker: `(speaker, matching voices)`.
    /// Speakers whose label equals the query come first, then labels containing
    /// it, then the rest, each in display order.
    pub fn search_speakers(&self, query: &str) -> Vec<(u32, Vec<u32>)> {
        let mut groups: Vec<Vec<u32>> = vec![Vec::new(); self.speakers.len()];
        for v in self.search(query) {
            for &sp in self.speakers_of_voice(v) {
                groups[sp as usize].push(v);
            }
        }
        let mut out: Vec<(u32, Vec<u32>)> = groups.into_iter().enumerate().filter(|(_, g)| !g.is_empty()).map(|(sp, g)| (sp as u32, g)).collect();
        let q = query.trim().to_lowercase();
        if !q.is_empty() {
            out.sort_by_key(|(sp, _)| {
                let label = self.speakers[*sp as usize].label.to_lowercase();
                if label == q {
                    0
                } else if label.contains(&q) {
                    1
                } else {
                    2
                }
            });
        }
        out
    }

    /// Who says it: the named speaker, else `Any <race> <sex>`.
    pub fn speaker_label(&self, idx: u32) -> String {
        let v = self.voice(idx);
        let l = self.line_of(v);
        if !l.speaker.is_empty() {
            l.speaker.to_string()
        } else {
            format!("Any {} {}", v.race, if v.female { "female" } else { "male" })
        }
    }

    /// Voices whose line, speaker, topic, quest, text, plugin or voice type
    /// contains every whitespace-separated token (ASCII case-insensitive).
    /// Empty query = everything, in display order.
    pub fn search(&self, query: &str) -> Vec<u32> {
        let tokens: Vec<String> = query.split_whitespace().map(|t| t.to_lowercase()).collect();
        if tokens.is_empty() {
            return (0..self.voices.len() as u32).collect();
        }
        // Per line: which tokens are satisfied by the line text alone.
        let line_hits: Vec<Vec<bool>> = self.haystack.iter().map(|h| tokens.iter().map(|t| h.contains(t.as_str())).collect()).collect();
        let mut out = Vec::new();
        for (i, v) in self.voices.iter().enumerate() {
            let hits = &line_hits[v.line as usize];
            let ok = tokens.iter().enumerate().all(|(ti, t)| {
                hits[ti]
                    || self.races_lc[v.voice_race_id as usize].contains(t.as_str())
                    || self.races_lc[v.race_id as usize].contains(t.as_str())
                    || (if v.female { "female" } else { "male" }) == t
                    || (v.alt && "alt".starts_with(t.as_str()))
                    || (t.bytes().all(|b| b.is_ascii_digit()) && v.wem_id.to_string().starts_with(t.as_str()))
            });
            if ok {
                out.push(i as u32);
            }
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_voice_index_loads() {
        let idx = VoiceIndex::get();
        assert!(idx.len() > 90_000, "{} voices", idx.len());
        assert!(idx.lines().len() > 19_000, "{} lines", idx.lines().len());
        let named = idx.lines().iter().filter(|l| l.named_speaker).count();
        assert!(named > 14_000, "{named} named lines");
        let with_text = idx.lines().iter().filter(|l| !l.text.is_empty()).count();
        assert!(with_text > 19_000, "{with_text} lines with text");
        for (i, v) in idx.voices.iter().enumerate() {
            assert!(idx.voices_of_wem(v.wem_id).contains(&(i as u32)));
        }
        assert!(idx.voices.iter().filter(|v| v.duration_ms > 0).count() > 90_000);
        // Recordings are shared between race folders (Dark Elf / Wood Elf / High Elf ...).
        let shared = idx.voices.iter().filter(|v| idx.voices_of_wem(v.wem_id).len() > 1).count();
        assert!(shared > 30_000, "{shared} voices share a recording");
        assert_eq!(idx.by_wem(0), None);
    }

    #[test]
    fn speaker_groups_cover_every_voice() {
        let idx = VoiceIndex::get();
        assert!(idx.speakers().len() > 1_000, "{}", idx.speakers().len());
        let total: usize = idx.speakers().iter().map(|s| s.voices.len()).sum();
        assert!(total >= idx.len());
        for (i, _) in idx.voices.iter().enumerate() {
            let sps = idx.speakers_of_voice(i as u32);
            assert!(!sps.is_empty());
            assert!(sps.iter().all(|&sp| idx.speaker(sp).voices.contains(&(i as u32))));
        }
        // Ordered: NPCs, then factions, classes and race groups.
        assert!(idx.speakers().windows(2).all(|w| w[0].kind <= w[1].kind));
        let sheo = idx.speakers().iter().find(|s| s.label == "Sheogorath").expect("Sheogorath");
        assert_eq!(sheo.kind, SpeakerKind::Npc);
        assert!(sheo.voices.len() > 100, "{}", sheo.voices.len());
        assert!(idx.speakers().iter().any(|s| s.kind == SpeakerKind::Race && s.label == "Any Orc female"));
        assert!(idx.speakers().iter().any(|s| s.kind == SpeakerKind::Faction));

        let groups = idx.search_speakers("sheogorath");
        assert_eq!(idx.speaker(groups[0].0).label, "Sheogorath");
        assert!(groups.len() > 1);
        assert!(groups.iter().all(|(_, v)| !v.is_empty()));
        let all = idx.search_speakers("");
        assert_eq!(all.len(), idx.speakers().len());
    }

    #[test]
    fn search_finds_speakers_topics_and_text() {
        let idx = VoiceIndex::get();
        let hits = idx.search("sheogorath");
        assert!(!hits.is_empty());
        assert!(hits.iter().all(|&i| {
            let v = idx.voice(i);
            let l = idx.line_of(v);
            l.speaker.to_lowercase().contains("sheogorath") || l.text.to_lowercase().contains("sheogorath") || v.race.to_lowercase().contains("sheogorath") || l.topic.to_lowercase().contains("sheogorath") || l.quest.to_lowercase().contains("sheogorath")
        }));
        let greeting_female_orc = idx.search("greeting orc female");
        assert!(!greeting_female_orc.is_empty());
        assert!(greeting_female_orc.iter().all(|&i| idx.voice(i).female));
        let label = idx.speaker_label(hits[0]);
        assert!(!label.is_empty());
    }
}
