//! Dialogue index: every voice recording in the game with the line it belongs
//! to (speaker, topic, quest, subtitle text) and its wem id.
//!
//! `assets/voice_index.bin` is generated by `tools/sfxindex` from the Wwise
//! voice events and the plugins' dialogue records, stored deflated and
//! inflated once on first use (~30 ms).

#[allow(dead_code)]
pub mod format;

use format::{RawVoiceIndex, LINE_NAMED_SPEAKER, NONE, VOICE_ALT};
use std::io::Read;
use std::sync::OnceLock;

static VOICE_BLOB: &[u8] = include_bytes!("../../assets/voice_index.bin");
static INDEX: OnceLock<VoiceIndex> = OnceLock::new();

#[derive(Clone, Debug)]
pub struct Line {
    pub formid: u32,
    pub plugin: &'static str,
    pub response: u8,
    /// The line is conditioned on specific NPCs (`speaker` names them).
    pub named_speaker: bool,
    pub quest: &'static str,
    pub topic: &'static str,
    pub text: &'static str,
    /// NPC names, a faction/class hint, or empty for "anyone of that race and sex".
    pub speaker: &'static str,
}

#[derive(Clone, Debug)]
pub struct Voice {
    pub wem_id: u32,
    pub line: u32,
    /// Race folder the event lives in.
    pub race: &'static str,
    pub female: bool,
    /// Race of the actor who recorded the file (can differ from `race`).
    pub voice_race: &'static str,
    pub alt: bool,
    pub duration_ms: u32,
}

impl Voice {
    /// `Imperial male`, `Dark Elf female (alt voice)`.
    pub fn voice_type(&self) -> String {
        let mut s = format!("{} {}", self.voice_race, if self.female { "female" } else { "male" });
        if self.alt {
            s.push_str(" (alt voice)");
        }
        s
    }
}

pub struct VoiceIndex {
    lines: Vec<Line>,
    voices: Vec<Voice>,
    by_wem: Vec<u32>,
    /// Lower-case searchable text per line: speaker, topic, quest, text, plugin.
    haystack: Vec<String>,
}

impl VoiceIndex {
    pub fn get() -> &'static VoiceIndex {
        INDEX.get_or_init(|| VoiceIndex::load(VOICE_BLOB).expect("embedded voice_index.bin is corrupt; rebuild it with tools/sfxindex"))
    }

    fn load(deflated: &'static [u8]) -> Result<VoiceIndex, format::FormatError> {
        let mut raw_bytes = Vec::with_capacity(deflated.len() * 4);
        flate2::read::DeflateDecoder::new(deflated)
            .read_to_end(&mut raw_bytes)
            .map_err(|e| format::FormatError(format!("inflate: {e}")))?;
        let blob: &'static [u8] = Box::leak(raw_bytes.into_boxed_slice());
        let raw = RawVoiceIndex::parse(blob)?;
        let h = raw.header;
        let str_or_empty = |id: u32| if id == NONE { "" } else { raw.string(id) };
        let races: Vec<&'static str> = (0..h.race_count as usize).map(|i| raw.string(raw.race(i))).collect();
        let plugins: Vec<&'static str> = (0..h.plugin_count as usize).map(|i| raw.string(raw.plugin(i))).collect();
        let lines: Vec<Line> = (0..h.line_count as usize)
            .map(|i| {
                let l = raw.line(i);
                Line {
                    formid: l.formid,
                    plugin: plugins.get(l.plugin as usize).copied().unwrap_or(""),
                    response: l.response,
                    named_speaker: l.flags & LINE_NAMED_SPEAKER != 0,
                    quest: str_or_empty(l.quest),
                    topic: str_or_empty(l.topic),
                    text: str_or_empty(l.text),
                    speaker: str_or_empty(l.speaker),
                }
            })
            .collect();
        let voices: Vec<Voice> = (0..h.voice_count as usize)
            .map(|i| {
                let v = raw.voice(i);
                Voice {
                    wem_id: v.wem_id,
                    line: v.line,
                    race: races[v.race as usize],
                    female: v.sex == 1,
                    voice_race: races[v.voice_race as usize],
                    alt: v.flags & VOICE_ALT != 0,
                    duration_ms: v.duration_ms,
                }
            })
            .collect();
        let by_wem = (0..h.voice_count as usize).map(|i| raw.by_wem(i)).collect();
        let haystack = lines
            .iter()
            .map(|l| format!("{}|{}|{}|{}|{}", l.speaker, l.topic, l.quest, l.text, l.plugin).to_lowercase())
            .collect();
        Ok(VoiceIndex { lines, voices, by_wem, haystack })
    }

    pub fn len(&self) -> usize {
        self.voices.len()
    }

    pub fn is_empty(&self) -> bool {
        self.voices.is_empty()
    }

    pub fn voice(&self, idx: u32) -> &Voice {
        &self.voices[idx as usize]
    }

    pub fn line_of(&self, voice: &Voice) -> &Line {
        &self.lines[voice.line as usize]
    }

    pub fn lines(&self) -> &[Line] {
        &self.lines
    }

    /// Voice index for a wem id (binary search).
    pub fn by_wem(&self, wem_id: u32) -> Option<u32> {
        self.by_wem
            .binary_search_by_key(&wem_id, |&i| self.voices[i as usize].wem_id)
            .ok()
            .map(|pos| self.by_wem[pos])
    }

    /// Who says it: the named speaker, else `Any <race> <sex>`.
    pub fn speaker_label(&self, idx: u32) -> String {
        let v = self.voice(idx);
        let l = self.line_of(v);
        if !l.speaker.is_empty() {
            l.speaker.to_string()
        } else {
            format!("Any {} {}", v.race, if v.female { "female" } else { "male" })
        }
    }

    /// Voices whose line, speaker, topic, quest, text, plugin or voice type
    /// contains every whitespace-separated token (ASCII case-insensitive).
    /// Empty query = everything, in display order.
    pub fn search(&self, query: &str) -> Vec<u32> {
        let tokens: Vec<String> = query.split_whitespace().map(|t| t.to_lowercase()).collect();
        if tokens.is_empty() {
            return (0..self.voices.len() as u32).collect();
        }
        // Per line: which tokens are satisfied by the line text alone.
        let line_hits: Vec<Vec<bool>> = self.haystack.iter().map(|h| tokens.iter().map(|t| h.contains(t.as_str())).collect()).collect();
        let mut out = Vec::new();
        for (i, v) in self.voices.iter().enumerate() {
            let hits = &line_hits[v.line as usize];
            let ok = tokens.iter().enumerate().all(|(ti, t)| {
                hits[ti]
                    || v.voice_race.to_lowercase().contains(t.as_str())
                    || v.race.to_lowercase().contains(t.as_str())
                    || (if v.female { "female" } else { "male" }) == t
                    || (v.alt && "alt".starts_with(t.as_str()))
                    || (t.bytes().all(|b| b.is_ascii_digit()) && v.wem_id.to_string().starts_with(t.as_str()))
            });
            if ok {
                out.push(i as u32);
            }
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_voice_index_loads() {
        let idx = VoiceIndex::get();
        assert!(idx.len() > 90_000, "{} voices", idx.len());
        assert!(idx.lines().len() > 19_000, "{} lines", idx.lines().len());
        let named = idx.lines().iter().filter(|l| l.named_speaker).count();
        assert!(named > 14_000, "{named} named lines");
        let with_text = idx.lines().iter().filter(|l| !l.text.is_empty()).count();
        assert!(with_text > 19_000, "{with_text} lines with text");
        for (i, v) in idx.voices.iter().enumerate() {
            assert_eq!(idx.by_wem(v.wem_id), Some(i as u32));
        }
        assert!(idx.voices.iter().filter(|v| v.duration_ms > 0).count() > 90_000);
    }

    #[test]
    fn search_finds_speakers_topics_and_text() {
        let idx = VoiceIndex::get();
        let hits = idx.search("sheogorath");
        assert!(!hits.is_empty());
        assert!(hits.iter().all(|&i| {
            let v = idx.voice(i);
            let l = idx.line_of(v);
            l.speaker.to_lowercase().contains("sheogorath") || l.text.to_lowercase().contains("sheogorath") || v.race.to_lowercase().contains("sheogorath") || l.topic.to_lowercase().contains("sheogorath") || l.quest.to_lowercase().contains("sheogorath")
        }));
        let greeting_female_orc = idx.search("greeting orc female");
        assert!(!greeting_female_orc.is_empty());
        assert!(greeting_female_orc.iter().all(|&i| idx.voice(i).female));
        let label = idx.speaker_label(hits[0]);
        assert!(!label.is_empty());
    }
}
